### ISSUE TITLE
[enhancement] "locate in explorer/finder" option

### ISSUE THREAD

**Issue by gordielachance** [tomahawk-player/tomahawk#425]
Hi guys,

What about an option to locate a file within the contextual menu for a track ?
This is really often really useful and it's quite a long to go to _properties > file_, then copy the path, paste it in explorer, .....

**Comment by dschmidt** [comment]
Yeah, should be doable. Maybe just for the current/best result (looping over all results might become expensive/slow for long lists with many resulsts), but doable

**Comment by gordielachance** [comment]
yeah !!!

**Comment by gordielachance** [comment]
First test with last nightly (tomahawk-0.8.99.20160220-git-master-8b904cf.exe) on windows 8: 

- local file > "open folder in file manager" > nothing happens
- remote file > crash when right clicking a track (here with  the Soundcloud resolver, not sure it does happens with every of them)

+ shouldn't it be named "reveal track in file manager" ? Ideally, the file manager should open the folder and highligh the selected track (should be possible since, for example, After Effects does it)

Maybe this could help ?

[How to “Reveal in Finder” or “Show in Explorer” with Qt](http://stackoverflow.com/questions/3490336/how-to-reveal-in-finder-or-show-in-explorer-with-qt)

**Comment by dschmidt** [comment]
Mh, it shouldn't crash after @muesli's fixes. Preselection yeah .... can do it at some point.

**Comment by gordielachance** [comment]
Yeah, it would be great as it doesn't help a lot to "locate" a track if it is lost in a directory containing a large amount of files...

**Comment by dschmidt** [comment]
We can't do anything better than that on Linux anyway ... :(

**Comment by dschmidt** [comment]
Crash is fixed in https://github.com/tomahawk-player/tomahawk/commit/015b24479c5a3dadf60bb9e91444947a6359fab5

**Comment by gordielachance** [comment]
still not working on Windows (8).  Nothing happens when I click "open folder in file manager" ...

**Comment by dschmidt** [comment]
Huh ... :-\ 

Need to investigate then...

**Comment by dschmidt** [comment]
As we have the feature now ... and it doesnt work, it qualifies as bug ;-)

**Comment by gordielachance** [comment]
I was also thinking that this could be used to locate remote files too.  
I mean, for example, clicking on the soundcloud icon when listening to a tracks goes to that track page on Soundcloud.  So it could maybe be extended to all that...
